# Generated by Django 5.2.8 on 2026-01-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingControl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Processing Control',
                'verbose_name_plural': 'AI Processing Controls',
                'db_table': 'tbl_ai_processing_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'db_table': 'tbl_ai_provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('batch_size', models.IntegerField(default=10)),
                ('batch_type', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annotation Batch',
                'verbose_name_plural': 'Annotation Batches',
                'db_table': 'tbl_annotation_batch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeGlobalMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Global Attribute',
                'verbose_name_plural': 'Global Attributes',
                'db_table': 'tbl_attribute_global_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attribute Master',
                'verbose_name_plural': 'Attribute Masters',
                'db_table': 'tbl_attribute_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_value', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Attribute Option',
                'verbose_name_plural': 'Attribute Options',
                'db_table': 'tbl_attribute_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeSubclassMap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Subclass Attribute Map',
                'verbose_name_plural': 'Subclass Attribute Maps',
                'db_table': 'tbl_attribute_subclass_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ingestion_batch', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('style_id', models.CharField(max_length=200)),
                ('style_desc', models.TextField(blank=True, null=True)),
                ('style_description', models.TextField(blank=True, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subdept_name', models.CharField(blank=True, max_length=200, null=True)),
                ('class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subclass_name', models.CharField(blank=True, max_length=200, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('pending_ai', 'Pending AI'), ('ai_in_progress', 'AI In Progress'), ('ai_done', 'AI Done'), ('pending_human', 'Pending Human'), ('human_in_progress', 'Human In Progress'), ('human_done', 'Human Done')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Product',
                'verbose_name_plural': 'Base Products',
                'db_table': 'tbl_base_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assignment_type', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], max_length=20)),
                ('assignment_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch Assignment',
                'verbose_name_plural': 'Batch Assignments',
                'db_table': 'tbl_batch_assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatchAssignmentItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_ai', 'Pending AI'), ('ai_in_progress', 'AI In Progress'), ('ai_done', 'AI Done'), ('pending_human', 'Pending Human'), ('human_in_progress', 'Human In Progress'), ('human_done', 'Human Done')], max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch Assignment Item',
                'verbose_name_plural': 'Batch Assignment Items',
                'db_table': 'tbl_batch_assignment_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_type', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch Item',
                'verbose_name_plural': 'Batch Items',
                'db_table': 'tbl_batch_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'lu_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'lu_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HumanAnnotator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Human Annotator',
                'verbose_name_plural': 'Human Annotators',
                'db_table': 'tbl_human_annotator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissingValueFlag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requested_value', models.TextField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Missing Value Flag',
                'verbose_name_plural': 'Missing Value Flags',
                'db_table': 'tbl_missing_value_flags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAnnotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], max_length=20)),
                ('source_id', models.BigIntegerField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Annotation',
                'verbose_name_plural': 'Product Annotations',
                'db_table': 'tbl_product_annotations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('ai', 'AI'), ('human', 'Human')], max_length=50)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
                'db_table': 'tbl_product_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color_id', models.CharField(max_length=200)),
                ('color_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'db_table': 'tbl_product_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'tbl_product_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('size_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('dim_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'db_table': 'tbl_product_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawProductData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, max_length=200, null=True)),
                ('style_id', models.CharField(max_length=200)),
                ('color_id', models.CharField(blank=True, max_length=200, null=True)),
                ('size_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('dim_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raw Product Data',
                'verbose_name_plural': 'Raw Product Data',
                'db_table': 'tbl_raw_product_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubClass',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Sub Class',
                'verbose_name_plural': 'Sub Classes',
                'db_table': 'lu_subclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Sub Department',
                'verbose_name_plural': 'Sub Departments',
                'db_table': 'lu_subdepartment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIProcessingRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempt', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_response', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_item', models.ForeignKey(blank=True, db_column='assignment_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='products.batchassignmentitem')),
                ('provider', models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_runs', to='products.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Processing Run',
                'verbose_name_plural': 'AI Processing Runs',
                'db_table': 'tbl_ai_processing_run',
                'managed': True,
                'indexes': [models.Index(fields=['provider', 'status'], name='tbl_ai_proc_provide_1cc94a_idx'), models.Index(fields=['assignment_item', 'status'], name='tbl_ai_proc_assignm_4cff6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIProviderFailureLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_item', models.ForeignKey(blank=True, db_column='assignment_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_logs', to='products.batchassignmentitem')),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='failure_logs', to='products.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Provider Failure Log',
                'verbose_name_plural': 'AI Provider Failure Logs',
                'db_table': 'tbl_ai_provider_failure_log',
                'managed': True,
                'indexes': [models.Index(fields=['provider', 'is_resolved'], name='tbl_ai_prov_provide_af09d8_idx'), models.Index(fields=['created_at'], name='tbl_ai_prov_created_f6feba_idx')],
            },
        ),
    ]
