# Generated by Django 5.2.8 on 2026-01-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_ai_provider_subclass_prompt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aiprovidersubclassprompt',
            name='unique_provider_subclass',
        ),
        migrations.RenameIndex(
            model_name='aiprovidersubclassprompt',
            new_name='tbl_ai_prov_provide_d1e64e_idx',
            old_name='idx_provider_subclass_active',
        ),
        migrations.AlterUniqueTogether(
            name='aiprovidersubclassprompt',
            unique_together={('provider', 'subclass')},
        ),
    ]
