# Generated by Django 5.2.8 on 2026-01-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_ai_global_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovidersubclassprompt',
            name='prompt_template',
            field=models.TextField(help_text='Custom prompt template for this provider-subclass combination. Use template variables: {{PRODUCT_INFO}}, {{ATTRIBUTES}}, {{IMAGE_INFO}}, {{STYLE_ID}}, {{NAME}}, {{DESCRIPTION}}, {{CATEGORY}}, {{SUBCATEGORY}}'),
        ),
    ]
